server:
  port: 8000

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gms.user.dao

# 打印sql
logging:
  level:
    com.gms.user.dao : debug

management:
  endpoints:
    web:
      exposure:
        include: "*"  # * 在yaml 文件属于关键字，所以需要加引号

