#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gms.user.dao