server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: "*"  # * 在yaml 文件属于关键字，所以需要加引号
spring:
  application:
    name: movie-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true