server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: "*"  # * 在yaml 文件属于关键字，所以需要加引号
spring:
  application:
    name: movie-server
  main:
    allow-bean-definition-overriding: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

user-server:
  ribbon:
    listOfServers: localhost:8000,localhost:8001